### ISSUE TITLE
High-quality rendering of graphs

### ISSUE THREAD

**Issue by unageek** [unageek/graphest#539]
### No anti-aliasing

```sh
cargo r --release -- -s 1024 1024 -- "y = sin(exp(x))" 
```

You get 2 shades of gray, black & white.

### 3x3 SSAA

```sh
cargo r --release -- -s 3074 3074 \
--padding-left 1 --padding-right 1 --padding-bottom 1 --padding-top 1 \
--dilate "1,1,1;1,1,1;1,1,1" \
-- "y = sin(exp(x))" 
```

→ Crop each side of the image by 1px, and resize it by 1/3.

```sh
convert graph.png -shave 1x1 -filter triangle -resize 1024x1024 graph2.png
```

You get 10 shades of gray.

### 5x5 SSAA

```sh
cargo r --release -- -s 5124 5124 \
--padding-left 2 --padding-right 2 --padding-bottom 2 --padding-top 2 \
--dilate "0,1,1,1,0;1,1,1,1,1;1,1,1,1,1;1,1,1,1,1;0,1,1,1,0" \
-- "y = sin(exp(x))" 
```

→ Crop each side of the image by 2px, and resize it by 1/5.

```sh
convert graph.png -shave 2x2 -filter triangle -resize 1024x1024 graph2.png
```

You get 26 shades of gray.

### 7x7 SSAA

```sh
cargo r --release -- -s 7174 7174 \
--padding-left 3 --padding-right 3 --padding-bottom 3 --padding-top 3 \
--dilate "0,0,1,1,1,0,0;0,1,1,1,1,1,0;1,1,1,1,1,1,1;1,1,1,1,1,1,1;1,1,1,1,1,1,1;0,1,1,1,1,1,0;0,0,1,1,1,0,0" \
-- "y = sin(exp(x))" 
```

→ Crop each side of the image by 3px, and resize it by 1/7.

```sh
convert graph.png -shave 3x3 -filter triangle -resize 1024x1024 graph2.png
```

You get 50 shades of gray.

### 9x9 SSAA

```sh
cargo r --release -- -s 9224 9224 \
--padding-left 4 --padding-right 4 --padding-bottom 4 --padding-top 4 \
--dilate "0,0,1,1,1,1,1,0,0;0,1,1,1,1,1,1,1,0;1,1,1,1,1,1,1,1,1;1,1,1,1,1,1,1,1,1;1,1,1,1,1,1,1,1,1;1,1,1,1,1,1,1,1,1;1,1,1,1,1,1,1,1,1;0,1,1,1,1,1,1,1,0;0,0,1,1,1,1,1,0,0" \
-- "y = sin(exp(x))" 
```

→ Crop each side of the image by 4px, and resize it by 1/9.

```sh
convert graph.png -shave 4x4 -filter triangle -resize 1024x1024 graph2.png
```

You get 82 shades of gray.

![graph2](https://user-images.githubusercontent.com/29035331/153829521-db4c9a83-4e8b-4afc-bd9a-66a08310a4e3.png)

The dilation kernels are obtained by Mathematica's `DiskMatrix[1]`, `DiskMatrix[2]`, etc.

**Comment by unageek** [comment]
Now this is possible with #540

**Comment by farteryhr** [comment]
just a note about gamma correction when doing anti-aliasing, this might sound nitpicking for most vector graphic software, but since we aim to be faithful... and yes there's already work done on more faithful image resizing: [imageworsener](http://entropymine.com/imageworsener/), it'll be nicer if we have this correction integrated or implemented.

**Comment by unageek** [comment]
@farteryhr Thank you for the suggestion!

Here is the gamma-corrected version of the 9x9 example:

![graph2](https://user-images.githubusercontent.com/29035331/166641187-e70f0e1f-efb2-4f60-ae6a-1ad9ae8f5750.png)

which is made by replacing the last command with:

```sh
convert graph.png -set colorspace RGB -shave 4x4 -filter triangle -resize 1024x1024 -colorspace sRGB graph2.png
```

**Comment by unageek** [comment]
Implemented in #692.

**Comment by farteryhr** [comment]
nice to have another step towards accuracy, but sorry for likely being deadly nitpicking....

about that shaving step (side cropping), i think it shouldn't happen. exactly like what subdivided interval arithmetic did, the samples should always be considered squares, not points, so do the pixels of the images. (also that means we could use even² subsample count with no trouble)

here are the even more serious discussion about it (by the author of ImageWorsener):
- [Match edges vs. match centers](http://entropymine.com/imageworsener/matching/) (it looks like you shave it in order to maintain the "center" or four corners)
- [Filters and fairness](http://entropymine.com/imageworsener/filterfairness/) (ImageMagick is discussed here)
- [Pixel mixing](http://entropymine.com/imageworsener/pixelmixing/) (this is preferred; i'm not sure what ImageMagick does)

btw, i'm also looking forward to more smart™/adaptive subdivision (maybe only for inequation with pen size 0 (also i think it should be default for inequations) on bilateral cases) that creates more levels of shades with less effort.

**Comment by unageek** [comment]
The match edges model is already used.

In 9x9 SSAA example, the image size (and accordingly, plot bounds) are extended by 4px on each side so that the dilated graph is valid across the original bounds (4px is the radius of the dilation kernel). This is what the options `--pad-left`, etc. do. Therefore, the original image (graph.png) has size 9224×9224 instead of 9216×9216. The side cropping is done to remove these paddings.

**Comment by farteryhr** [comment]
got it, didn't notice that extension :facepalm:
