### ISSUE TITLE
Improve performance of dilation with large kernels

### ISSUE THREAD

**Issue by unageek** [unageek/graphest#543]
### Input
A graph _g_ (`Image::<Ternary>`) and a kernel _ker_ (`Image::<bool>`).

### Output
The dilated graph _g_out_ (`Image::<Ternary>`).

### Algorithm

1. Decompose _g_ into two images:
   _g_t_ ← true pixels mapped to 1 and the others to 0,
   _g_u_ ← uncertain pixels mapped to 1 and the others to 0.
2. Apply FFT to _g_t_, _g_u_, and _ker_.
3. _g_t_ ← _g_t_ ⊙ _ker_,
   _g_u_ ← _g_u_ ⊙ _ker_.
4. Apply IFFT to _g_t_ and _g_u_.
5. _g_out_ ← non-zero pixels of _g_t_ mapped to true, other non-zero pixels of _g_u_ mapped to uncertain, and the others set to false.
   Note that the non-zero test may require some threshold.

**Comment by farteryhr** [comment]
any plan on vector tracing and curve offseting for antialiasing, instead of bitmap dilation? though somehow risky, but potentially energy-saving for smoother picture for most nice functions. (i.e. other than real `^` and gcd and some other discrete monsters).

this might help: https://pomax.github.io/bezierinfo/#offsetting

**Comment by unageek** [comment]
Hi!

I think dilation by convolution as currently implemented is not so slow. However, it is certainly an interesting topic to produce error-bounded vector traces of line-like graphs (or more)!
